export type Room = {
  path: string;
  id: string;
  name: string;
  verb: string;
  note: string;
  paper: string;
  ink: string;
  dust: string;
  accent: string;
  bloom: string;
  sky: string;
  invert: boolean;
  inkRgb: [number, number, number];
};

export const rooms: Room[] = [
  {
    path: "/",
    id: "home",
    name: "Home",
    verb: "Arrive",
    note: "A clear place to land",
    paper: "#f3eee6",
    ink: "#161412",
    dust: "#8a8175",
    accent: "#c45c26",
    bloom: "#ead9a8",
    sky: "#efe4cc",
    invert: false,
    inkRgb: [0.09, 0.07, 0.05],
  },
  {
    path: "/rooms",
    id: "rooms",
    name: "Rooms",
    verb: "Wander",
    note: "Fourteen rooms, fourteen weathers",
    paper: "#f3f0e8",
    ink: "#1a221c",
    dust: "#7a8478",
    accent: "#5f8a72",
    bloom: "#e8cfc0",
    sky: "#cfe0da",
    invert: false,
    inkRgb: [0.22, 0.32, 0.26],
  },
  {
    path: "/breathe",
    id: "breathe",
    name: "Breathe",
    verb: "Live",
    note: "Match the room’s pulse",
    paper: "#dceee8",
    ink: "#16332c",
    dust: "#5d7a72",
    accent: "#3e8f82",
    bloom: "#b7ddd4",
    sky: "#f4faf7",
    invert: false,
    inkRgb: [0.18, 0.42, 0.36],
  },
  {
    path: "/dawn",
    id: "dawn",
    name: "Dawn",
    verb: "Wake",
    note: "A sky you can move",
    paper: "#f3d5c4",
    ink: "#2a2018",
    dust: "#8a6e60",
    accent: "#e08a4a",
    bloom: "#f0b48a",
    sky: "#7eabc8",
    invert: false,
    inkRgb: [0.82, 0.48, 0.28],
  },
  {
    path: "/pond",
    id: "pond",
    name: "Pond",
    verb: "Still",
    note: "Touch, then let it settle",
    paper: "#c5ddd8",
    ink: "#16332c",
    dust: "#4f736c",
    accent: "#2f6b6a",
    bloom: "#9ec9c0",
    sky: "#e7f3f0",
    invert: false,
    inkRgb: [0.16, 0.38, 0.36],
  },
  {
    path: "/bloom",
    id: "bloom",
    name: "Bloom",
    verb: "Grow",
    note: "Leave something living",
    paper: "#f6e6dc",
    ink: "#3a241c",
    dust: "#8a6a60",
    accent: "#d4786a",
    bloom: "#f0c8b4",
    sky: "#e8dcc8",
    invert: false,
    inkRgb: [0.78, 0.4, 0.36],
  },
  {
    path: "/hum",
    id: "hum",
    name: "Hum",
    verb: "Listen",
    note: "Pluck a quiet tone",
    paper: "#1c1830",
    ink: "#f4eefc",
    dust: "#b8a8d0",
    accent: "#d4b8f0",
    bloom: "#6a5a9a",
    sky: "#2a2448",
    invert: true,
    inkRgb: [0.7, 0.55, 0.88],
  },
  {
    path: "/release",
    id: "release",
    name: "Release",
    verb: "Let go",
    note: "Hold until it becomes light",
    paper: "#2a1c18",
    ink: "#f3eee6",
    dust: "#c9b2a4",
    accent: "#d4784a",
    bloom: "#8a3a22",
    sky: "#3a2420",
    invert: true,
    inkRgb: [0.72, 0.32, 0.18],
  },
  {
    path: "/letters",
    id: "letters",
    name: "Letters",
    verb: "Settle",
    note: "Words that can rest",
    paper: "#f4ead6",
    ink: "#2a2214",
    dust: "#8a7a5c",
    accent: "#c4a35a",
    bloom: "#ead9a8",
    sky: "#efe4cc",
    invert: false,
    inkRgb: [0.55, 0.42, 0.18],
  },
  {
    path: "/weather",
    id: "weather",
    name: "Weather",
    verb: "Gather",
    note: "Your hand is the climate",
    paper: "#121826",
    ink: "#f0ebe3",
    dust: "#9aa4b8",
    accent: "#e2b15a",
    bloom: "#3a4a72",
    sky: "#1a2236",
    invert: true,
    inkRgb: [0.72, 0.52, 0.22],
  },
  {
    path: "/walk",
    id: "walk",
    name: "Walk",
    verb: "Wander",
    note: "A hallway of quiet color",
    paper: "#161412",
    ink: "#f3eee6",
    dust: "#b7aea4",
    accent: "#cfe0da",
    bloom: "#c45c26",
    sky: "#2a2622",
    invert: true,
    inkRgb: [0.78, 0.72, 0.62],
  },
  {
    path: "/hold",
    id: "hold",
    name: "Hold",
    verb: "Open",
    note: "Rooms that wait for you",
    paper: "#e7eee4",
    ink: "#1c2618",
    dust: "#6d7c68",
    accent: "#5f7d55",
    bloom: "#d5e4c8",
    sky: "#c5d4c0",
    invert: false,
    inkRgb: [0.28, 0.4, 0.24],
  },
  {
    path: "/return",
    id: "return",
    name: "Return",
    verb: "Come home",
    note: "Nothing stays stretched",
    paper: "#efe6d8",
    ink: "#2a2218",
    dust: "#8a7a68",
    accent: "#8c6a4a",
    bloom: "#e2c8a8",
    sky: "#ddd0c0",
    invert: false,
    inkRgb: [0.4, 0.28, 0.16],
  },
  {
    path: "/depth",
    id: "depth",
    name: "Depth",
    verb: "Sink",
    note: "There is no destination",
    paper: "#0b0d10",
    ink: "#e8e6e0",
    dust: "#8e949e",
    accent: "#c9d4e0",
    bloom: "#2a3344",
    sky: "#141820",
    invert: true,
    inkRgb: [0.78, 0.82, 0.88],
  },
  {
    path: "/ink",
    id: "ink",
    name: "Ink",
    verb: "Mark",
    note: "Play without a score",
    paper: "#ece7dc",
    ink: "#1a2430",
    dust: "#6e7a86",
    accent: "#3d5c7a",
    bloom: "#c5d4e0",
    sky: "#d8cfc2",
    invert: false,
    inkRgb: [0.22, 0.32, 0.48],
  },
  {
    path: "/company",
    id: "company",
    name: "Company",
    verb: "Meet",
    note: "A gentle knock among friends",
    paper: "#cfe3dc",
    ink: "#16332c",
    dust: "#5a7a72",
    accent: "#2f6b5d",
    bloom: "#e8c9a0",
    sky: "#f3eee6",
    invert: false,
    inkRgb: [0.16, 0.36, 0.3],
  },
];

export function roomByPath(path: string) {
  const clean = path.replace(/\/+$/, "") || "/";
  return rooms.find((r) => r.path === clean) ?? rooms[0];
}

export function nextRoom(path: string) {
  const current = roomByPath(path);
  const i = rooms.findIndex((r) => r.id === current.id);
  return rooms[(i + 1) % rooms.length];
}

export const destinations = rooms.filter((r) => r.id !== "home" && r.id !== "rooms");
